import type { Metadata } from "next";
    import { GeistSans } from "geist/font/sans";
    import { GeistMono } from "geist/font/mono";
    import "@/styles/globals.css"; // Use correct path
    import { cn } from "@/lib/utils"; // Use correct path

    export const metadata: Metadata = {
      title: "DecideX Board Portal", // Updated title
      description: "Generated by v0.dev, reconstructed",
    };

    export default function RootLayout({
      children,
    }: Readonly<{
      children: React.ReactNode;
    }>) {
      return (
        <html lang="en" className={cn(GeistSans.variable, GeistMono.variable)}>
          {/* Add suppressHydrationWarning if needed based on errors */}
          <body suppressHydrationWarning={true}>{children}</body>
        </html>
      );
    }